#!/usr/bin/env php
<?php

$phingPhpFilePath = __DIR__ . '/vendor/phing/phing/bin/phing.php';

if (!file_exists($phingPhpFilePath)) {
    echo "Error: $phingPhpFilePath not found.\n";
    echo "Please run: composer install\n";
    exit(1);
}

// turn off html errors
ini_set('html_errors', 'off');

putenv('PHING_HOME=' . realpath(dirname($phingPhpFilePath)));

require_once $phingPhpFilePath;
